# Default application configuration.

simplecov:
  report_path:
    - public/coverage/.last_run.json
  coverage_path:
    - 'result,line'

rubycritc:
  report_path:
    - tmp/rubycritic/report.json
  score_path:
    - score

cloc:
  report_path:
    - stats.json
  total_lines_path:
    - 'header,n_lines'
  total_files_path:
    - 'header,n_files'
  ignored_directories:
    - 'tmp,public,node_modules,vendor'

brakeman:
  errors_path:
    - 'scan_info,errors'
  security_warnings_path:
    - 'scan_info,security_warnings'
  ignored_warnings_path:
    - 'scan_info,ignored_warnings'

google_spreadsheet:
  spreadsheet_id:
  # todo clean after updating readme
  client_secret: '{"type":"","project_id":"","private_key_id":"", "private_key":"", "client_email":"", "client_id":"", "auth_uri":"", "token_uri":"", "auth_provider_x509_cert_url":"", "client_x509_cert_url":""}'

libraries:
  - cloc
  - simplecov
  - brakeman
  - rubycritic
